openapi: 3.0.0
components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas:
    Notification:
      properties:
        deviceToken:
          type: string
        notificationId:
          type: string
      required:
        - deviceToken
        - notificationId
      type: object
      additionalProperties: false
    Moment:
      properties:
        id:
          type: string
        date:
          type: integer
          format: date-time
        time:
          type: object
          properties:
            EU:
              type: integer
              format: date-time
            US:
              type: integer
              format: date-time
            WA:
              type: integer
              format: date-time
            EA:
              type: integer
              format: date-time
      required:
        - id
        - timestamp
      type: object
      additionalProperties: false
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
info:
  title: Push Notification Gateway API
  version: 1.0.0
  description: Internal API used by dailyZap to deliver Push Notifications to App Users and provide the daily timestamps.
paths:
  /v1/notifications:
    post:
      operationId: SendNotifications
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      tags:
        - Push Notifications
      security:
        - apiKey: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                notifications:
                  type: array
                  items:
                    $ref: '#/components/schemas/Notification'
  /v1/auth/check:
    get:
      operationId: CheckAuth
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      tags:
        - Authentication
      security:
        - apiKey: []
      parameters: []
  /v1/moments:
    get:
      operationId: GetMoments
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  moments:
                    type: array
                    items:
                      $ref: '#/components/schemas/Moment'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      tags:
        - Moments
      security:
        - apiKey: []
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            maximum: 30
            minimum: 1
          description: Limit the number of moments to return
        - name: after
          in: query
          required: false
          schema:
            type: integer
            format: date-time
          description: Return moments after this timestamp
servers:
  - description: Local Development
    url: http://localhost:5173/api
